anniou21/Glorytime

config/routes.rb

Please review and merge
@EtienneTes @ArafathN

Pages removal

---

app/views/booking_items/create.html.erb
app/views/booking_items/delete.html.erb
app/views/booking_items/index.html.erb
app/views/bookings/create.html.erb
app/views/watches/create.html.erb
app/views/watches/delete.html.erb

Please review and merge.
@ArafathN

Updated views: removed unused ones

---

config/routes.rb

@ArafathN 
Some stuff to review and merge

New routes

---

app/controllers/booking_items_controller.rb
app/controllers/bookings_controller.rb
app/controllers/shops_controller.rb
app/controllers/watches_controller.rb
app/views/booking_items/new.html.erb
app/views/booking_items/update.html.erb
app/views/bookings/edit.html.erb
app/views/shops/index.html.erb
app/views/watches/new.html.erb
config/routes.rb

New Routes checked by Cecile

---

app/views/shared/_navbar.html.erb
app/views/watches/index.html.erb

bugfix routings

---

app/views/watches/index.html.erb

Pages#home2

---

app/assets/stylesheets/components/_banner.scss
app/views/pages/home.html.erb

Add a searchbar for example

---

db/seeds.rb

Ordered Seeds

---

app/controllers/booking_items_controller.rb
app/controllers/bookings_controller.rb
app/models/booking.rb
app/models/shop.rb
app/models/user.rb
app/views/bookings/show.html.erb
app/views/shared/_navbar.html.erb

Updated Models with relationships

---

app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb
app/views/bookings/show.html.erb
db/migrate/20191127160624_remove_start_end_dates_from_bookings.rb
db/migrate/20191127160638_add_status_to_booking_items.rb
db/migrate/20191127160646_add_start_end_dates_to_booking_items.rb
db/seeds.rb

Model changes

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_watches.scss
app/controllers/watches_controller.rb
app/javascript/packs/application.js
app/javascript/plugin/map.js
app/models/booking.rb
app/views/watches/show.html.erb
db/seeds.rb

Maj day3 seeds

---

db/migrate/20191127160624_remove_start_end_dates_from_bookings.rb
db/migrate/20191127160646_add_start_end_dates_to_booking_items.rb
db/migrate/20191127164332_remove_end_date_from_bookings.rb
db/migrate/20191127164432_remove_start_date_from_bookings.rb
db/migrate/20191127164624_add_start_dateto_booking_items.rb
db/migrate/20191127164637_add_end_dateto_booking_items.rb
db/migrate/20191127164950_add_end_date_to_booking_items.rb
db/migrate/20191127165000_add_start_date_to_booking_items.rb
db/migrate/20191127165407_add_status_to_booking_items.rb
db/schema.rb
db/seeds.rb

Models updated

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_features-block.scss
app/assets/stylesheets/components/_fonts.scss
app/assets/stylesheets/components/_grid-watches.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search-bar.scss
app/assets/stylesheets/components/_watches-show.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/watches/index.html.erb
app/views/watches/show.html.erb

Wacthes#show

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_features-block.scss
app/assets/stylesheets/components/_fonts.scss
app/assets/stylesheets/components/_grid-watches.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search-bar.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/watches/index.html.erb

Watches#index3

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_features-block.scss
app/assets/stylesheets/components/_fonts.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search-bar.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

Watches#index2

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_fonts.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search-bar.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

Searchbar implemented

---

app/controllers/booking_items_controller.rb
app/controllers/bookings_controller.rb
app/controllers/watches_controller.rb
app/models/shop.rb
app/views/bookings/index.html.erb
app/views/bookings/show.html.erb
db/seeds.rb

@ArafathN keep only my changes to controllers and views

Booking @ Booking_item updated + seeds

---

app/assets/stylesheets/components/_watches-show.scss
app/controllers/watches_controller.rb
app/views/shared/_navbar.html.erb

Navigation for navbar

---

app/assets/stylesheets/components/_index.scss
app/views/bookings/index.html.erb
app/views/shared/_navbar.html.erb

Add a new style

---

app/assets/stylesheets/components/_button.scss
app/views/watches/index.html.erb

Bugfix watches#index

---

app/controllers/booking_items_controller.rb
app/views/bookings/basket.html.erb
app/views/watches/show.html.erb
db/migrate/20191129123254_add_cost_to_booking_items.rb
db/migrate/20191129124449_add_cost_per_day_to_watches.rb
db/schema.rb

Added cost and cost per day to models

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_watches-show.scss
app/controllers/watches_controller.rb
app/views/watches/show.html.erb

Watches#show11 - new title

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_watches-show.scss
app/controllers/watches_controller.rb
app/views/watches/show.html.erb

Watches#show10

---

app/views/shared/_navbar.html.erb

ModifNavBar

---

app/assets/stylesheets/components/_grid-watches.scss
app/assets/stylesheets/components/_watches-show.scss
app/views/dashboards/show.html.erb
app/views/shared/_navbar.html.erb
app/views/watches/index.html.erb
app/views/watches/show.html.erb

for read @EtienneTes @C2drik @ArafathN

Watchshowdisplay

---

app/assets/stylesheets/components/_grid-watches.scss
app/assets/stylesheets/components/_watches-show.scss
app/views/dashboards/show.html.erb
app/views/shared/_navbar.html.erb
app/views/watches/index.html.erb
app/views/watches/show.html.erb

Watchesdisplay

---

app/views/dashboards/show.html.erb

Stylized dashboard

---

app/assets/stylesheets/components/_grid-watches.scss
app/views/watches/index.html.erb

Add a padding on a watches img

---

app/assets/stylesheets/components/_watches-show.scss
app/controllers/bookmarks_controller.rb
app/views/watches/show.html.erb

Flashes notice for action

---

app/models/booking_item.rb
app/views/dashboards/show.html.erb
db/migrate/20191203154444_add_sku_to_watches.rb
db/schema.rb
db/seeds.rb

Bugfix seeds and stripe payement

---

db/migrate/20191204092205_add_sku_to_watches.rb
db/schema.rb

Bugfix Sky to watches

---

app/views/watches/index.html.erb

@anniou21 @C2drik @EtienneTes 
Modif dans Searchbar, now in French

SearchbarModif

---

app/views/shared/_footer.html.erb
app/views/watches/index.html.erb

@anniou21 @C2drik @EtienneTes 
Retiré Google + du Footer

Remove google+from footer

---

app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/watches/index.html.erb

@anniou21 @C2drik @EtienneTes 
Correction des coquilles dans la Home

Correction ortho home

---

app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
app/views/watches/index.html.erb

@C2drik @EtienneTes @anniou21 
Traduction en français des éléments de la Navbar

Modif navbar

---

app/views/dashboards/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
app/views/watches/index.html.erb

@C2drik @EtienneTes @anniou21 
Traduction en français des élements du Dashboard

Correction dashboard

---

app/assets/stylesheets/components/_dashboard.scss
app/assets/stylesheets/components/_search-bar.scss
app/views/dashboards/show.html.erb
app/views/watches/index.html.erb

Fix of Searchbar
@anniou21 @EtienneTes @C2drik

Searchbar2

---

app/assets/stylesheets/components/_dashboard.scss
app/assets/stylesheets/components/_search-bar.scss
app/views/dashboards/show.html.erb

Dashboard searchfix

---

app/assets/stylesheets/components/_dashboard.scss

SearchbarStatutDashboard

---

app/assets/stylesheets/components/_dashboard.scss
app/views/dashboards/show.html.erb

@anniou21 @EtienneTes 
Boutons du Dashboard

SearchbarDash

---

app/assets/stylesheets/components/_booking.scss
app/assets/stylesheets/components/_grid-watches.scss
app/views/bookings/show.html.erb

page fade panier

---

app/assets/stylesheets/components/_booking.scss
app/controllers/booking_items_controller.rb
app/views/bookings/show.html.erb
app/views/pages/home.html.erb
app/views/payments/new.html.erb

wip - forget push by Kevin

---

app/views/watches/show.html.erb

Wording du Watch#Show

---

app/assets/stylesheets/components/_dashboard.scss
app/views/dashboards/show.html.erb
app/views/watches/show.html.erb

Wording dash#show

---

app/assets/stylesheets/components/_dashboard.scss
app/views/dashboards/show.html.erb
app/views/watches/show.html.erb

Wording jour

---

app/views/dashboards/show.html.erb

@anniou21 @C2drik @EtienneTes 
Add Select status to Dash

SelectStatustoDash

---

app/views/bookings/show.html.erb

WordingBooking#Show

---

app/controllers/booking_items_controller.rb
app/views/watches/show.html.erb

Ajouter Panier redirection vers l'index

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_grid-watches.scss
app/assets/stylesheets/components/_search-bar.scss
app/assets/stylesheets/components/_watches-show.scss
app/controllers/bookmarks_controller.rb
app/views/dashboards/show.html.erb
app/views/pages/home.html.erb
app/views/payments/new.html.erb
app/views/watches/index.html.erb
app/views/watches/show.html.erb

bugfix sur quelques pages

---

app/views/dashboards/show.html.erb

Dash#Show5

---

app/views/dashboards/show.html.erb

Bugfix dashbaord

---

app/views/pages/home.html.erb

Wording#Home

---

app/assets/stylesheets/components/_watches-show.scss
app/views/watches/index.html.erb
app/views/watches/show.html.erb

Index price

---

app/assets/stylesheets/components/_watches-show.scss
app/views/watches/index.html.erb
app/views/watches/show.html.erb

Prixdevente

---

db/seeds.rb

Bugfix seeds
